
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  PROJECT="simple"
  RUNDECK_YUM_REPO="https://bintray.com/rundeck/rundeck-rpm/rpm"

  IP="192.168.50.30"

  config.vm.define :deployer do |deployer|
    deployer.vm.hostname = "deployer"
    deployer.vm.network :private_network, ip: "#{IP}"
    deployer.vm.provision :shell, :path => "nexus/install.sh", :args => "#{IP}"
    deployer.vm.provision :shell, :path => "jenkins/install.sh", :args => "#{IP}"
    deployer.vm.provision :shell, :path => "rundeck/install.sh", :args => "deployer #{IP} #{RUNDECK_YUM_REPO}"
    deployer.vm.provision :shell, :path => "rundeck/add-project.sh", :args => "#{IP} #{PROJECT}"
    deployer.vm.provision :shell, :path => "rundeck/install-rundeck-admin.sh", :args => "http://#{IP}:4440"
  end

 config.vm.define :app1 do |app1|
    app1.vm.hostname = "app1"
    app1.vm.network :private_network, ip: "192.168.50.31"
    app1.vm.provision :shell, :path => "tomcat/install.sh", :args => "192.168.50.31 http://#{IP}:4440 #{PROJECT}"
  end


end

